# Useful resources:
# https://medium.com/@abulka/getting-python-and-wxpython-apps-into-the-ubuntu-app-store-ccca7ae537a3
# https://github.com/om26er/opencv-cuda-snap/blob/master
name: chimpstackr
adopt-info: chimpstackr # Used to get version from git tags
summary: Focus stacking software
description: |
  ChimpStackr is a program that can be used for focus stacking many images.
  Focus stacking is often a necessity when working with high-magnification pictures.

base: core20
grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  chimpstackr:
    command-chain:
      - usr/local/bin/snapcraft-preload # Fixes multiprocessing python module
    command: bin/chimpstackr
    extensions:
      - kde-neon
    plugs:
      - home
      - removable-media

parts:
  snapcraft-preload:
    source: https://github.com/sergiusens/snapcraft-preload.git
    plugin: cmake
    build-packages:
      - on amd64:
        - gcc-multilib
        - g++-multilib
    stage-packages:
      - lib32stdc++6
    # Copy ".so" files from usr/local/bin to $SNAP/bin
    override-prime: |
      snapcraftctl prime
      mkdir -p $SNAPCRAFT_PRIME/lib
      cp $SNAPCRAFT_PRIME/usr/local/lib/libsnapcraft-preload.so $SNAPCRAFT_PRIME/lib/libsnapcraft-preload.so
      if [ ${SNAP_ARCH} = "amd64" ]; then cp $SNAPCRAFT_PRIME/usr/local/lib/libsnapcraft-preload32.so $SNAPCRAFT_PRIME/lib/libsnapcraft-preload32.so; fi

  chimpstackr:
    plugin: python
    source: .
    requirements: ['requirements.txt']
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe --tags --abbrev=0)
    build-packages:
      - libxkbfile-dev
      - libtbb-dev
    stage-packages:
      - libxkbcommon0
      - libgtk-3-0
      - libxkbfile1
      - gstreamer1.0-gl
      - libtbb2
    after:
      - snapcraft-preload